#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# polybar
polybar workspaces &
polybar playing &
polybar widgets &

# feh background
~/.fehbg &

# key bindings
sxhkd &

# unclutter (hides mouse while typing)
unclutter -idle 2 &

# picom
picom --experimental-backends -b

# start redshift
redshift -t 6500:5100 -l geoclue2 &

# rofi greenclipboard daemon
greenclip daemon &

# Set some bsp specific stuff
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# bspwm settings
bspc config border_width 0
bspc config window_gap 5
bspc config top_padding 30
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod1
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# some window rules

# always float feh
bspc rule -a feh state=floating follow=on

# map apps to desktops
# 1 > terminal
bspc rule -a kitty desktop='^1' follow=on focus=on
# 2 > web
bspc rule -a Brave-browser desktop='^2'
# 3 > telegram
bspc rule -a KotatogramDesktop desktop='^3'
# 5 > file manager
bspc rule -a Nemo desktop='^5' follow=on focus=on
# 6 > office
bspc rule -a DesktopEditors desktop='^6' follow=on focus=on
bspc rule -a Xreader desktop='^6' follow=on focus=on
# 8 > music
bspc rule -a spotify desktop='^8'
